E_liabrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('',include('readbook.urls')),
]

accounts/urls.py
from django.urls import path, include
from . import views


app_name= "Accounts"
urlpatterns = [
    path('register/',views.register_user,name="register_user"),
    path('login/', views.login_user, name="login_user"),
    path('logout/', views.logout_user, name="logout_user"),

]

readbook/urls.py
from django.urls import path
from . import views

app_name="readbook"
urlpatterns = [
    path('',views.loadbook,name="premiumbook",)
]

accounts/models.py
from django.db import models

readbook/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth
from django.contrib import messages


def register_user(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']
            username =request.POST['username']
            email =request.POST['email']
            user_type = request.POST['user_type']
            password1 =request.POST['password1']
            password2 =request.POST['password2']

            if password1 == password2:
                if User.objects.filter(username=username).exists():
                    messages.info(request, "Username is already exists !")
                elif User.objects.filter(email=email).exists():
                    messages.info(request, 'Email is already exists !')
                    return redirect('Accounts:register_user')
                else:
                    user = User.objects.create_user(username=username, password=password1, email=email, first_name=first_name, last_name=last_name)
                    user.save()
                    return redirect('/')
            else:
                messages.info(request, "Password didn't match !")
                return redirect('Accounts:register_user') 
        return render(request, 'accounts/register.html')


def login_user(request):
    if not request.user.is_authenticated:
        if request.method =='POST':
            username = request.POST['username']
            password = request.POST['password']

            user = auth.authenticate(username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect('/')
            else:
                messages.info(request, 'invalid credential!')
                return redirect('Accounts:login_user')
        else:
            return render(request, 'accounts/login.html')
    return redirect('/')

def logout_user(request):
    auth.logout(request)
    return redirect("Accounts:login_user")

readbook/views.py
from django.shortcuts import render

templates/accounts/login.html
{% extends "base.html" %} {% block content %}

<div class="container mt-5">
  <div class="row">
    <div class="offset-3 col-md-6">
      <div class="m-2 text-center">
        <h1>Login</h1>
      </div>
      {% if messages %} {% for message in messages %}
      <div class="m-2 p-2 rounded alert-danger" id="alert">{{message}}</div>
      {% endfor %} {% endif %}
      <form action="" method="post">
        {% csrf_token %}

        <div class="form-group">
          <input
            required
            class="form-control"
            type="text"
            name="username"
            placeholder="Username"
            id=""
          />
        </div>

        <div class="form-group">
          <input
            required
            class="form-control"
            type="password"
            name="password"
            id=""
            placeholder="Enter Your Password"
          />
        </div>

        <input
          type="submit"
          name="Login"
          value="Login"
          class="btn btn-primary w-100"
        />
      </form>
      <div class="m-2">
        <h3>
          Create an Account?
          <a href="{% url 'Accounts:register_user' %}">Register Here</a>
        </h3>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/accounts/register.html
{% extends "base.html" %} {% block content %}

<div class="container mt-5">
  <div class="row">
    <div class="offset-3 col-md-6">
      <div class="m-2 text-center">
        <h1>Register</h1>
      </div>

      {% if messages %} {% for message in messages %}
      <div class="m-2 p-2 rounded alert-danger" id="alert">{{message}}</div>
      {% endfor %} {% endif %}
      <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
          <input
            required
            class="form-control"
            type="text"
            name="first_name"
            id=""
            placeholder="First Name"
          />
        </div>
        <div class="form-group">
          <input
            required
            class="form-control"
            type="text"
            name="last_name"
            placeholder="Last Name"
            id=""
          />
        </div>
        <div class="form-group">
          <input
            required
            class="form-control"
            type="text"
            name="username"
            placeholder="Username"
            id=""
          />
        </div>
        <div class="form-group">
          <input
            required
            class="form-control"
            type="email"
            name="email"
            placeholder="Enter Your Email"
            id=""
          />
        </div>
        <div class="form-group">
          <label for="author">Choose Type : </label>
          <select name="user_type" id="">
            <option value="Reader">Reader</option>
            <option value="Author">Author</option>
          </select>
        </div>

        <div class="form-group">
          <input
            required
            class="form-control"
            type="password"
            name="password1"
            id=""
            placeholder="Enter Your Password"
          />
        </div>
        <div class="form-group">
          <input
            required
            class="form-control"
            type="password"
            name="password2"
            id=""
            placeholder="Enter Your Password"
          />
        </div>

        <input
          type="submit"
          name="Register"
          value="Register"
          class="btn btn-primary w-100"
        />
      </form>
      <div class="m-2">
        <h3>
          Already have an Account?
          <a href="{% url 'Accounts:login_user' %}">Login Here</a>
        </h3>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>E-liabrary</title>

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">E-Liabrary</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          {% if request.user.is_authenticate %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Accounts:logout_user' %}"
              >Logout</a
            >
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Accounts:register_user' %}"
              >Register</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Accounts:login_user' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    {% block content %} {% endblock content %}

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
  </body>
</html>